### ISSUE TITLE
linter-markdown can’t recognized secondary list

### ISSUE THREAD

**Issue by 764582402** [AtomLinter/linter-markdown#117]
linter-markdown can`t recognized secondary list item , report me as "remark-lint Error remark-lint:list-item-bullet-indent Incorrect indentation before bullet: remove 2 spacesat line 2 col 3" .

``` mardown
*   Theme
  + `atom-material-syntax`：SublimeText
  + `Nucleus Dark UI`：
```

**Comment by wooorm** [comment]
Thanks, @764582402!

This is not a bug, it’s a feature. Sure, that’s a nested list in some markdown flavours, but it isn’t in some others (for example, commonmark doesn’t support those list items).

So, the warning is apt: either remove two spaces if you want one list, or add a space to create a nested list.

Does this help?

**Comment by JeanMertz** [comment]
Commonmark does support nested lists, if you use four spaces (unfortunately, linter-markdown does not):

```
- hello
    - world
    - universe
```

http://commonmark.org/help/tutorial/10-nestedLists.html

**Comment by Arcanemagus** [comment]
@wooorm Isn't this issue better suited for [remark-lint](https://github.com/wooorm/remark-lint)? I'm not sure how this would be fixed here.

**Comment by wooorm** [comment]
@JeanMertz Pretty sure both

```md
- hello
    - world
    - universe
```

...and...

```md
-   hello
    - world
    - universe
```

...are supported. I’m not sure what you see as “linter-markdown does not [support nested lists]”, but if there’s a problem, `remark-lint` or `remark` is the best place to report an issue.
