### ISSUE TITLE
remark-lint error: Cannot process given file: It's ignored at line 0 col 0

### ISSUE THREAD

**Issue by swinton** [AtomLinter/linter-markdown#120]
I'm receiving this error from `remark-lint` (_Cannot process given file: It's ignored at line 0 col 0_) on my `.github/issue_template.md`, but I am not sure what is causing this file to be ignored.

![screenshot 2017-01-03 14 46 40](https://cloud.githubusercontent.com/assets/27806/21622519/785578be-d1c3-11e6-9ed8-ede6012973b6.png)

Other files appear to be processed without issue.

Any thoughts? :pray: :bow:

**Comment by wooorm** [comment]
It's the dot in the '.github' directory. Sorry about that.
It should be fixed in the close future: https://github.com/wooorm/unified-engine/issues/2.

**Comment by swinton** [comment]
Many thanks for the reference, @wooorm.

I've subscribed to https://github.com/wooorm/unified-engine/issues/2, I'll close this issue 👍

**Comment by wooorm** [comment]
Cheers! ❤️

**Comment by dodekeract** [comment]
I'm having the same error on a `readme.md` file.
