### ISSUE TITLE
Problems with Atom 1.8 (or node8/npm5)?

### ISSUE THREAD

**Issue by kachkaev** [AtomLinter/linter-markdown#142]
Hi guys,

I upgraded to atom 1.8 and stopped seeing markdown errors in the editor. Command-line markdown linting still works as well as in-editor eslint/prettier.

If I'm not alone with this problem, shall we start an investigation? If no one else turns up in a few days, let's just close the issue.

__UPD__ Maybe it's an issues with node8/npm5 compatibility?

**Comment by wooorm** [comment]
For me stuff is working fine? 😬 Maybe someone else?

**Comment by kachkaev** [comment]
Was able to fix this after upgrading deps:

```diff
-    "remark-cli": "^2.0.0",
-    "remark-lint": "^5.0.1"
-    "remark-preset-lint-recommended": "^1.0.0",
+    "remark-cli": "^3.0.1",
+    "remark-lint": "^6.0.0",
+    "remark-preset-lint-recommended": "^2.0.0"
```

These were the deps of our team's common plugin (formerly preset), so it was not immediately clear that the major version bumped. Linting via CLI still worked, which is not a surprise.

If Atom plugin is not compatible with the older `remark`, maybe it could warn that somehow? :–)
