### ISSUE TITLE
Yaml Frontmatter

### ISSUE THREAD

**Issue by mcnesium** [AtomLinter/linter-markdown#148]
In [Atom](https://atom.io) it's marking errors in the YAML frontmatter of jekyll markdown files

![screenshot](https://user-images.githubusercontent.com/476060/28720696-35c02548-73ae-11e7-88b1-cec14f7f1ac7.png)

This is a false flag and should not be marked imho.

Also, it does not recognize comments in the frontmatter:

![screenshot2](https://user-images.githubusercontent.com/476060/28720757-679c9c18-73ae-11e7-8d62-3b7053bd664c.png)

Originally reported [here](https://github.com/wooorm/remark-lint/issues/154)

**Comment by Arcanemagus** [comment]
@wooorm Shouldn't plugins be supported as of v4.1.0 (https://github.com/AtomLinter/linter-markdown/pull/143)?

So this should be a "simple" matter of adding `remark-frontmatter` to the `devDependencies` of @mcnesium's project, and adding it to the `plugins` section of `.remarkrc`, right?

**Comment by wooorm** [comment]
Yes, `npm install -g remark-frontmatter`, and create a `.remarkrc` somewhere that contains the linting config you want, plus `remark-frontmatter`. For example, in your home folder (`~/.remarkrc`):

```
{
  "plugins": [
    "frontmatter",
    "preset-lint-markdown-style-guide"
  ]
}
```

**Comment by mcnesium** [comment]
So I need to install remark-frontmatter to *each* of my markdown projects? Wouldn't it be easier to just add it to the package dependencies of the package that actually uses it? Or am I getting something wrong here?

**Comment by wooorm** [comment]
No, not entirely.

If you’re using this linter, and are not using remark through other means (e.g., the CLI) you can `npm install -g remark-frontmatter` and [presets or rules](https://github.com/wooorm/remark-lint#list-of-presets) once (which installs them globally).

Then, if you have zero `.remarkrc` files, add the one I pasted above in your home directory.
If you do have `.remarkrc` files already, add `remark-frontmatter` to all of them.

@Arcanemagus I’m open to including `remark-frontmatter` here, potentially, what do you think?

**Comment by Arcanemagus** [comment]
@wooorm If you think it's something most people would be using I don't see why not. This is meant to be the "use to lint markdown if you don't need the more advanced config of `linter-remark`" if I understand things correctly. 😛

**Comment by wooorm** [comment]
True! Should `toml` be supported to? Should they be configurable?

**Comment by Arcanemagus** [comment]
I don't know anything about the Markdown linting ecosystem, so you tell me 😛.

**Comment by wooorm** [comment]
Thanks for releasing this @Arcanemagus! You’re the best! 👍

**Comment by Arcanemagus** [comment]
Sorry I missed it till just now 😉.
