### ISSUE TITLE
Support "fix on save"

### ISSUE THREAD

**Issue by VincentBel** [AtomLinter/linter-markdown#152]
Currently we can only view the lint issues and correct them manually. But some of the errors can be fixed automatically. It would be great if has a "fix on save" config.

Besides, this is supported by [linter-eslint](https://github.com/AtomLinter/linter-eslint) package.

![image](https://user-images.githubusercontent.com/6076919/31478826-b1f82baa-aed8-11e7-91aa-e8a3d24c7daf.png)

**Comment by wooorm** [comment]
Hi @VincentBel! 👋

Unfortunately blocked by wooorm/remark-lint#82!
