### ISSUE TITLE
Erroneous Judgement for parsedown-rubytext when using parsedown

### ISSUE THREAD

**Issue by windawings** [AtomLinter/linter-markdown#159]
using code like:
[原文]^(yuán wén)
[评论]^(comments)
Erroneous Judgement, wish to add whitelist or filter.

**Comment by wooorm** [comment]
@windawings Sorry, I don’t understand what you mean. Could you check out this [`contributing.md`](https://github.com/remarkjs/remark/blob/master/contributing.md) file for inspiration on how to help me debug your problem?

**Comment by windawings** [comment]
@wooorm I'm sorry for not checking out your document. Now I'm aware of this issue making no sense for markdown specification, which is just a custom feature, sorry for my ignorance again.
