### ISSUE TITLE
False Positive on markdown comment

### ISSUE THREAD

**Issue by roycetech** [AtomLinter/linter-markdown#174]
Markdown comment is being tagged as `Found unused definition`.

For example:
`[//]: # (@lang=xml)`

OS: MacOS High Sierra 10.13.6
Atom version: 1.28.2 x64
Package version: 5.2.2

**Comment by wooorm** [comment]
🤔 how is that a markdown comment?

**Comment by wooorm** [comment]
Markdown doesn’t have comments. It does allow embedding HTML though, and you can use HTML comments: `<!-- some thing -->`.
