### ISSUE TITLE
Add support for `mdastConfig` in package.json

### ISSUE THREAD

**Issue by pmmenneg** [AtomLinter/linter-markdown#18]
Would be great if the plugin could read the [`mdast`](https://github.com/wooorm/mdast/blob/master/doc/mdastrc.5.md) supported `mdastConfig ` block from our project's package.json file.

**Comment by SpainTrain** [comment]
I think this should work.  Does `mdast-lint` work as expected from CLI (https://github.com/wooorm/mdast-lint)?

**Comment by pmmenneg** [comment]
Here's my `mdastConfig` from `package.json`:

```json
"mdastConfig": {
  "plugins": {
    "lint": {
        "list-item-indent": "space",
        "maximum-line-length": 79,
        "emphasis-marker": "*",
        "strong-marker": "*"
    }
  }
}
```

Note that the command line tool does not seem to be reading from either the local .mdastrc file, nor the package.json, while Atom, which I am using to lint, does read correctly from .mdastrc.

**Comment by wooorm** [comment]
Seems mdast has a bug :anguished:

**Comment by wooorm** [comment]
I’ve got a fix coming up. However, that should’t be the reason for linter-markdown to support only `.mdastrc` files and ignore `package.json` files?

**Comment by pmmenneg** [comment]
I've updated to the latest 2.3.2, but cli still an issue - I can point it at either of the .mdastrc, or package.json, but it's not respecting the config in either file - I am seeing warnings that per the above config should be disabled (specifically, `Incorrect list-item indent: add 2 spaces  list-item-indent`)

**Comment by wooorm** [comment]
OK, weird. Could you raise on issue on mdast’s repo? With info like node version, and a minimal set-up which fails for you?

And if you’re on unix: run `DEBUG="*" mdast .`!

**Comment by pmmenneg** [comment]
Ok, I believe the `mdast` cli is working as expected. Running that command it now respects the `.mdastrc` file, and whn I remove that file, I can see in the debug state that it is falling back to `package.json`. So that is good. The bad? My original issue with respect to `linter-markdown` remains - removing the `.mdastrc` file results in a linting using the default settings, rather than the `package.json` file. Anything I can try to debug that aspect?

**Comment by wooorm** [comment]
Ok. Good to hear.

In that case, have you uninstalled and re-installed linter-markdown?

**Comment by wooorm** [comment]
@pmmenneg Ping!

**Comment by wooorm** [comment]
Closed due to no response.
