### ISSUE TITLE
Not working for Adam Notes

### ISSUE THREAD

**Issue by jkamenik** [AtomLinter/linter-markdown#251]
[Atom Notes](https://github.com/lexicalunit/atom-notes) sets the source to `source.gfm.notes` so I have made the "Scopes" setting: `source.gfm, source.pfm, text.md, source.gfm.notes`.  However the linter is still not picking up Atom Note markdown files.

Not sure what else to change.

**Comment by Arcanemagus** [comment]
What does the `Linter: Debug` command show in a file that you expect to see results in but don't?

**Comment by jkamenik** [comment]
Well, part of the issue was `language-atom-notes` was making the source `source.gfm.notes`.  I have disabled it as well as `language-gfm` and enabled `language-markdown` and things work as expected.

So I solved my issue, and I am not sure if having a 3rd level source is a valid.  If it is valid, then there still might be a defect, but if it isn't a valid configuration then we can close this issue.

**Comment by Arcanemagus** [comment]
You can configured the scopes that `linter-markdown` runs on in the settings, with the default ones being:
https://github.com/AtomLinter/linter-markdown/blob/6066a92cb4b5901ac2332f4c0d3fc2a15fbf0f69/package.json#L114-L127
