### ISSUE TITLE
Atom linter not using configuration from ~/.remarkrc

### ISSUE THREAD

**Issue by eppsilon** [AtomLinter/linter-markdown#29]
Hi,

I had a `~/.mdastrc` file that was working prior to updating this plugin recently. It looks like mdast is now remark, so I renamed my config file to `~/.remarkrc`. I also installed remark (3.1.3) and remark-lint (2.0.3) globally via npm.

Running `remark [markdown file]` gives me the linter output that I would expect with my rules applied: 7 warnings. But I don't see the same output in Atom - I get 31 errors for the same file. What could I do to figure out why the Atom linter is not respecting my configuration?

Here is the contents of `~/.remarkrc`:

```json
{
  "output": true,
  "plugins": {
    "remark-lint": {
      "blockquote-indentation": 2,
      "emphasis-marker": "_",
      "final-newline": true,
      "first-heading-level": true,
      "hard-break-spaces": true,
      "heading-increment": true,
      "list-item-indent": "space",
      "maximum-line-length": 99999,
      "no-multiple-toplevel-headings": false,
      "strong-marker": "*"
    }
  },
  "settings": {
    "commonmark": true,
    "gfm": true,
    "bullet": "-",
    "listItemIndent": "1"
  }
}
```

**Note**: The documentation for remark/remark-lint says `"remark-lint"` (under `"plugins"`) should just be `"lint"`, but that produced an error when running remark.

```
1:1  error    Error: Cannot find module 'lint'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at findPlugin (/usr/local/lib/node_modules/remark/lib/cli/file-pipeline/configure.js:140:12)
    at /usr/local/lib/node_modules/remark/lib/cli/file-pipeline/configure.js:199:26
    at handleLocalConfiguration (/usr/local/lib/node_modules/remark/lib/cli/configuration.js:294:9)
    at /usr/local/lib/node_modules/remark/lib/cli/configuration.js:211:9
    at /usr/local/lib/node_modules/remark/node_modules/vfile-find-up/index.js:207:17
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by wooorm** [comment]
Thanks for raising this issue, @eppsilon, have you also updated linter-markdown? `linter-markdown` uses a local `remark` and `remark-lint` installation (thus in previous versions, `mdast` and `mdast-lint`).
If you’re on the latest, please uninstall and reinstall `linter-markdown`, and check if that solves the problems.

About the short-name: if `remark` is globally installed, and `remark-lint` is globally install too, you *should* be able to omit the `remark-` prefix. The same applies when both are installed locally, but when mixing things might go awry.
If you have the time, please raise an issue on [remark](https://github.com/wooorm/remark/issues) if my words above don’t hold true in your case :)

Back to `linter-markdown`. If an update to `linter-markdown` didn’t fix it, hmm, then I’d like some more information about the directory your working in, your OS, atom/apm versions, list of your atom plugins, etc. But in that case I’m not sure what the problem might be.

**Comment by eppsilon** [comment]
Yes, I was using version 1.3.0 of linter-markdown. I haven't tried reinstalling it yet.

Re: short-name - I created [an issue on remark](https://github.com/wooorm/remark/issues/131) for that problem.

**Comment by wooorm** [comment]
@eppsilon Have you already tried re-installing? And if that works, could you close this issue?

**Comment by wooorm** [comment]
@eppsilon Ping!

**Comment by AleksanderLevadniy** [comment]
@wooorm Hi, Titus! I've got similar issue. I've got Atom with **linter** and **linter-markdown** plugins + `.remarkrc` with such content:

``` json
{
  "plugins": {
    "remark-lint": {
      "no-missing-blank-lines": false,
      "list-item-bullet-indent": false,
      "list-item-content-indent": false,
      "list-item-indent": "mixed",
      "list-item-spacing": false,
      "maximum-line-length": 80
    }
  }
}
```

Problem is that if I'm using remark from command line it's all right, but Atom refuses to use `.remarkrc` file for `.md` validation. If `remark-lint` key in `plugins` section will be replaced with `lint` then I'm having opposite situation: command line refused to apply `.remarkrc`, but it works perfectly in Atom.

Remark and remark-lint are installed using `--global` flag.

**Comment by wooorm** [comment]
1. What node version are you using?
1. Can you uninstall and re-install both the global dependencies, and the atom linter?
1. Can you show me the files and the directories?

**Comment by AleksanderLevadniy** [comment]
@wooorm Thank you for so reactive answer!

1. node: v5.3.0
2. I've already trying to reinstall in different ways with/without `--global` flag + linter
3. I have `.remarkrc` in root of my work folder and many subfolders with `README.md` files

For example:

/root
   .remarkrc
   /subroot1
       README.md
   /subroot2
       README.md 

I'm using following command to check all my files using mark:
 `find . -name "*.md" -print0 | xargs -n 1 -0 remark -f`

**Comment by wooorm** [comment]
What are the exact results of `find . -name "*.md" -print0`?

And, why not use `remark .`?

**Comment by AleksanderLevadniy** [comment]
For `find . -name "*.md" -print0 | xargs -n 1 -0 echo` I got this:

./process/style/requirement tempate/README.md
./process/tools/android/README.md
./process/tools/general/README.md
./process/tools/ios/README.md
./README.md

Folders may contain not only `.md` files so this if done for filtering purpose

**Comment by AleksanderLevadniy** [comment]
With 'remark-lint' this script works perfectly but Atom failing to get my rules in `.remarkrc` file

**Comment by wooorm** [comment]
I understand, but `remark` [searches for markdown files](https://github.com/wooorm/remark/blob/master/doc/remark.1.md#description).

* Back to atom, have you uninstalled and re-installed linter-markdown?
* Could it be there’s a `lint`, `lint.js` file next to the `.remarkrc` file?

**Comment by AleksanderLevadniy** [comment]
@wooorm 

1. Yes, I've already done this plenty of times.
2. No, there is no such file as `lint` beside `.remarkrc`

**Comment by wooorm** [comment]
Could you show me the output of `DEBUG="*" remark .`?

**Comment by AleksanderLevadniy** [comment]
[remark.txt](https://github.com/AtomLinter/linter-markdown/files/117907/remark.txt)

**Comment by wooorm** [comment]
And it’s correct that there are no warnings reported, right?

**Comment by wooorm** [comment]
One more thing, I think I’ve almost got it. Could you show `DEBUG="*" remark .` when using `"lint"` instead of `"remark-lint"` inside your `.remarkrc`?

**Comment by AleksanderLevadniy** [comment]
@wooorm Here it goes
[remark.txt](https://github.com/AtomLinter/linter-markdown/files/117926/remark.txt)

**Comment by wooorm** [comment]
Are you sure there’s no file or module called `lint` somehere? e.g., in the current working directory, or in the root of your project (where your `package.json` is)? See these paths: https://github.com/wooorm/remark/blob/6c38cc7ff0260bcceea106ad54474e0eb8966159/lib/cli/file-pipeline/configure.js#L75-L89

**Comment by AleksanderLevadniy** [comment]
@wooorm  Here is `ls -la` output from my working directory:

-rw-r--r--   1 alevadniy  staff  271 Feb  4 20:16 .remarkrc
-rw-r--r--   1 alevadniy  staff  195 Feb  4 19:32 .travis.yml
-rw-r--r--   1 alevadniy  staff   53 Feb  4 15:40 README.md
drwxr-xr-x   9 alevadniy  staff  306 Feb  3 13:14 process

**Comment by wooorm** [comment]
Is there a `package.json` above? Is there a `lint` in globally installed npm modules?

**Comment by AleksanderLevadniy** [comment]
@wooorm Nope, no `package.json` is above. No there is no lint module under npm.

**Comment by AleksanderLevadniy** [comment]
@wooorm Fix works great! When it'll be ready for release?

**Comment by wooorm** [comment]
Now!

**Comment by cwilli34** [comment]
I still cannot get the maximum-line-length to change, or any settings to take effect from modifying the .remarkrc file in the root of the package in the Atom settings.  Why does the .remarkrc file not affect the linter-markdown package?

**Comment by Arcanemagus** [comment]
@cwilli34 Can you file a new issue? This has been closed for 4 months and it's likely you are running into a different issue than what was discussed here (especially since this was fixed!).
