### ISSUE TITLE
Customise default lint rules

### ISSUE THREAD

**Issue by speedRS** [AtomLinter/linter-markdown#31]
Based on the following line in the documentation:

> The linting is easily configurable with remark-lint.

That implies to me that I should be using a .remarkrc file. What is unclear to me is where that file lives in relation to atom.io. I assumed it would be somewhere under ~/.atom (on Mac) and wouldn't rely on an external instance of remark-lint and a ~/.remarkrc file. 

Let me know if I'm completely off base.

**Comment by Arcanemagus** [comment]
Like most configuration files it should be project based and live at the root of each project. That way everyone working on the project gets the same configuration.

If for some reason that doesn't work for you, usually you can put a configuration file in your home directory (assuming all projects are within that), or some other parent folder for all your projects. @wooorm can confirm as he is the author of the linter as well as the maintainer of this package :wink:.

**Comment by wooorm** [comment]
Yes, it is as @Arcanemagus mentioned. The third and fourth items on the [Cascade docs for `.remarkrc`](https://github.com/wooorm/remark/blob/master/doc/remarkrc.5.md#cascade) apply here.

I can imagine that being a bit hard to find out though, do you have suggestions regarding what we could do to get this information across more easily?

**Comment by wooorm** [comment]
@speedRS Ping!

**Comment by danielbayley** [comment]
As I mention here on the main `linter` repo ([#1056](https://github.com/atom-community/linter/issues/1056))…

> While I agree that when working on large/r projects, config files should be kept with the project; I think it’s good to have a global config for each linter as a fallback if one doesn’t exist. Also what if I have a bunch of smaller/private projects which I want to share a common config?

> As it stands, some linter- packages have this option and others don’t. This inconsistency leads to this seemingly unnecessary “meta" configuration headache. Often the suggestion is to further pollute the HOME directory with yet another . file, which I don’t want to do.

This `linter-` package currently doesn’t have a setting to specify a custom config. In this case, looking at the `remark -h`elp, it could be done by passing `-c ~/path/to/default/config.json` to the underlying `remark` binary.

[`linter-sass-lint`](https://github.com/AtomLinter/linter-sass-lint) is a good example of having these options.

**Comment by Arcanemagus** [comment]
@danielbayley What you are talking about is overriding the configuration automatically found by the linter, not where to place the configuration for proper detection in the first place, which is what this issue is about.

(Though a PR for that functionality would be nice, as there are people that use that for some reason :wink:)

**Comment by wooorm** [comment]
Agreed, as that’s a different issue, I’d suggest opening a separate report.

However, I’m not interested in building it. PRs are welcome though.
