### ISSUE TITLE
Nested lists throw an Error

### ISSUE THREAD

**Issue by Wabuo** [AtomLinter/linter-markdown#34]
Like I said in the title it is impossible to crate Nested lists without getting an error.
[Markdown Basics / Nested lists] (https://help.github.com/articles/markdown-basics/#nested-lists)

**Comment by Arcanemagus** [comment]
What do you mean by errors?

The example given in your link has many _lint_ errors, but doesn't cause any crashes.

If you meant you can't figure out how to clean up the lint errors, here is that same example fixed according to the default ruleset:
```markdown
1.  Item 1

    1.  A corollary to the above item.
    2.  Yet another point to consider.

2.  Item 2

    *   A corollary that does not need to be ordered.

        *   This is indented four spaces, because it's two spaces further than
            the item above.

        *   You might want to consider making a new list.

3.  Item 3
```

**Comment by Wabuo** [comment]
>If you meant you can't figure out how to clean up the lint errors, here is that same example fixed according to the default ruleset:
Yes I was talking about lint errors. Locks like I jus was a little stuck in a rut =).
