### ISSUE TITLE
Allow Tabs?

### ISSUE THREAD

**Issue by dodekeract** [AtomLinter/linter-markdown#37]
I'm sorry if this is obvious, but I can't find any way to allow/force hard-tabs instead of spaces. I always get annoying "remark-lint Error no-tabs Use spaces instead of hard-tabs" errors.

**Comment by wooorm** [comment]
* see the [no-tabs](https://github.com/wooorm/remark-lint/blob/master/doc/rules.md#no-tabs) rule, this is giving you warnings;
* read the docs on [how to configure rules](https://github.com/wooorm/remark-lint#configuring-remark-lint);
* next time please open questions regarding remark-lint, on remark-lint's repo!

Good luck :)
