### ISSUE TITLE
Disable option

### ISSUE THREAD

**Issue by brunowego** [AtomLinter/linter-markdown#57]
Add a option for disable if not has presence of `.remarkrc` in the project. :+1:

**Comment by SangSatori** [comment]
Whoops, sorry about polluting the reference section after realizing the commit message doesn't look _just right_ on GitHub.

**Comment by wooorm** [comment]
As mentioned in https://github.com/AtomLinter/linter-markdown/pull/91, instead of using `linter-markdown`, use [`linter-remark`](https://github.com/wooorm/linter-remark), and set up `.remarkrc`s in the directories you want to get linted, with something like `"plugins": ["lint"]`!
