### ISSUE TITLE
.remarkrc changes do take effect in any project

### ISSUE THREAD

**Issue by cwilli34** [AtomLinter/linter-markdown#62]
I still cannot get the maximum-line-length to change, or any settings to take effect from modifying the .remarkrc file in the root of the package in the Atom settings. Why does the .remarkrc file not affect the linter-markdown package?  I actually had to change the maximum-line-length in .atom/linter-markdown/node_modules/remark-lint/rules/maximum-line-length.js from 80 to 120 for the linter to actually  stop giving me warnings about line-length of 80.

**Comment by Arcanemagus** [comment]
Can you outline the directory structure showing the relevant locations of the file you are seeing this issue on and the configuration file you are expecting to affect it? Or even easier just upload a zip of the folder or point to the repository?

Does `remark-lint` from the CLI work properly?

**Comment by cwilli34** [comment]
The file I had to change to get maximum-line-length to not show me a warning in Atom was at .atom/linter-markdown/node_modules/remark-lint/rules/maximum-line-length.js

The .remarkrc file is in the linter-markdown directory at .atom/linter-markdown/.remarkrc

It is this file in this repository: [.remarkrc](https://github.com/AtomLinter/linter-markdown/blob/master/.remarkrc)

Any changes to the .remarkrc file does nothing in any of my projects when it comes to the warnings in Atom using the linter-markdown package.

And is remark-lint supposed to be installed globally?  Because it seems to work inside Atom just fine, except for the not reading the .remarkrc file.  But if I do `remark-lint` from the command line, the command does not exist.  But all the node modules for remark-lint and remark are installed.

Here is a copy of my linter-markdown package within the .atom directory:
[linter-markdown.zip](https://github.com/AtomLinter/linter-markdown/files/249340/linter-markdown.zip)

**Comment by wooorm** [comment]
That’s our own `.remarkrc`. It does not affect your project.

You must instead add `.remarkrc` files in your own projects, or in your home directory. See this [doc](https://github.com/wooorm/remark/blob/master/doc/remarkrc.5.md#cascade) for more info.

And on another note: no you don’t need to install remark / remark-lint yourself.

**Comment by cwilli34** [comment]
So I cannot change the default behavior then of the add-on?

**Comment by wooorm** [comment]
> [...] add .remarkrc files [...] in your home directory.
