### ISSUE TITLE
Support validate-links

### ISSUE THREAD

**Issue by namuol** [AtomLinter/linter-markdown#69]
I use [remark-validate-links](https://github.com/wooorm/remark-validate-links) to ensure I'm not including broken links in my documentation. It'd be great if I could catch those mistakes right inside Atom! :)

I'm guessing the underlying reason this isn't supported out of the box is due to the fact that there's [no programmatic API for `remark-validate-links`](https://github.com/wooorm/remark-validate-links/tree/4d88bc69b7ff284f7485bc23f1330650305c9535#programmatic); is that correct?

**Comment by wooorm** [comment]
Yes, it’s currently not possible. 😢

However, I’m working on externalising the CLI of remark, which would make it easier to use it directly in this project. It’ll take some time though!

**Comment by namuol** [comment]
I'd be happy to take a stab at a PR to add the necessary programmatic API to `remark-validate-links`, if you think it's something worth having. :beers:

**Comment by wooorm** [comment]
@namuol, @kucherenkovova You can now you [linter-remark](https://atom.io/packages/linter-remark), which is like this package except that it support all remark plugins. It also differs in that `linter-remark` *needs* an `.remarkrc` file to do things!

As I don’t believe this feature should be in this project, I’m closing it here!
