### ISSUE TITLE
Linting Entire Markdown File as Bash

### ISSUE THREAD

**Issue by austinbutler** [AtomLinter/linter-markdown#7]
Originally I added the language to the triple backticks per the suggestion of markdown linter. When the language is set to shell it seems to then start doing Bash/shellcheck linting on the whole file, including the markdown.

For example:
```
error
Tips depend on target shell and yours is unknown. Add a shebang. [SC2148]at line 1 col 1
warning
Quote this to prevent word splitting. [SC2046]at line 7 col 1
warning
Quote this to prevent word splitting. [SC2046]at line 7 col 3
warning
Quote this to prevent word splitting. [SC2046]at line 9 col 2
warning
Quote this to prevent word splitting. [SC2046]at line 11 col 1
warning
Quote this to prevent word splitting. [SC2046]at line 11 col 3
```

Example Markdown file (corrently using .md on my end, had to rename for Github):
[grav.txt](https://github.com/AtomLinter/linter-markdown/files/35082/grav.txt)

**Comment by Arcanemagus** [comment]
This is almost certainly another side effect of https://github.com/atom/language-gfm/issues/121, I would recommend trying out [language-markdown](https://atom.io/packages/language-markdown) as a replacement to fix this issue.

Marking as closed since this is an upstream bug.
