### ISSUE TITLE
Update mdast

### ISSUE THREAD

**Issue by wooorm** [AtomLinter/linter-markdown#8]
From ^1.0.0 to ^2.0.0.

I think that would close wooorm/mdast#102 and wooorm/mdast#97.

There was already a PR for this, but the author PRed on their own fork (brettz9/linter-markdown#1) instead of this one.

Also a heads-up: somewhere the coming week I’m probably pushing 3.0.0

**Comment by Arcanemagus** [comment]
Enabled greenkeeper on this repo, so whenever a dependency updates beyond the range allowed currently we should get a PR :wink:.

**Comment by wooorm** [comment]
:+1:

**Comment by Arcanemagus** [comment]
Published in v1.2.2.

@wooorm would you be interested in maintaining this package? Or are you still interested in working on this @leipert?

**Comment by wooorm** [comment]
I’d rather not. But if I’m allowed to rewrite in plain-JavaScript, I just might :wink:

**Comment by Arcanemagus** [comment]
That would be awesome, the core `linter` and helper libraries have already moved over as most of the maintainers prefer it :wink:.

If you are interested just let me know and we will do what we can to help out!

**Comment by wooorm** [comment]
OK, cool. I have a lot on my plate currently, but I’ve already done wooorm/atom-linter-alex in plain-JS, so rewriting won’t take a while.

In other words: if anyone would like to take control now, please do, otherwise, please give me access to the repo and I’ll do “my best”.

**Comment by Arcanemagus** [comment]
At the recommendation of @steelbrain and the fact that you already have a linter plugin written it sounds like a plan :wink:.

**Comment by Arcanemagus** [comment]
You should have an invitation to join this repo's team waiting in your inbox. Let us know if you have any questions!

**Comment by wooorm** [comment]
Yes, I received it. Thanks, will do!

**Comment by SpainTrain** [comment]
> I’ll do “my best”

That's all any of us do :grin: 

mdast/mdast-lint and alex are nice projects, btw! :ok_hand:

**Comment by wooorm** [comment]
Haha, great to hear! Thanks!

**Comment by leipert** [comment]
@wooorm @SpainTrain 	@Arcanemagus 

Hey there. Sorry for the long abscence. 
I am glad I moved this package to @AtomLinter.
Good that you stepped in @wooorm. Actually makes a lot of sense that you are a maintainer, as you also maintain mda... *ahem* sorry: remark-lint.

If there is any stuff I can help with, just ping me. I am trying to be more responsive on github again, the last months have been crazy busy, but it is going to better now.

**Comment by Arcanemagus** [comment]
@leipert Life happens :wink:

If you see something you feel needs fixing, send in a PR, if you want access to a repository you may no longer have, just speak up. We have a #linter-plugin-dev channel on Atom's Slack if you want to chat there about anything.

**Comment by wooorm** [comment]
@leipert No problem! And I agree w/ @Arcanemagus sentiment :)
