### ISSUE TITLE
configuration comments no longer work

### ISSUE THREAD

**Issue by UziTech** [AtomLinter/linter-markdown#97]
`<!--lint disable list-item-indent-->` at thee top of the file does not disable `list-item-indent`

This used to work. 

Most likely this is an issue with remark-lint but I do not have time to debug it.

**Comment by wooorm** [comment]
I cannot reproduce. Works fine for me!

* Have you tried restarting Atom?
* Do you have an old version of remark-lint installed locally?

**Comment by UziTech** [comment]
- Restarted Atom
- Not sure how to check for local remark-lint, but I don't think so

**Comment by UziTech** [comment]
Atom: v1.9.9
linter-markdown: v2.0.1

Windows 10 build 14901

**Comment by wooorm** [comment]
You can check your locally installed dependencies by running `npm ls --depth=0`.

* Also, do you see `remark` or `remark-lint` when running `npm ls -g --depth=0` (that checks globally installed deps), and if so, what versions to they have?

**Comment by UziTech** [comment]
Oh locally to the project. No I don't have remark or remark-lint locally or globally.

**Comment by wooorm** [comment]
Thanks for looking, weird!

Could you show the markdown you tried, which failed?

**Comment by UziTech** [comment]
I figured it out. apparently there has to be a blank line after the comment or it doesn't work

**Comment by wooorm** [comment]
That was exactly my guess with my previous comment! :)

Yeah, for those comments to be detect they must be on their own line. Has to do with markdown parsing. I should add that to the docs somewhere!
